export const GET_ACTIVITY_LIST = 'GET_ACTIVITY_LIST'
export const GET_ACTIVITY_LIST_REQUEST = 'GET_ACTIVITY_LIST_REQUEST'
export const GET_ACTIVITY_LIST_SUCCESS = 'GET_ACTIVITY_LIST_SUCCESS'
export const GET_ACTIVITY_LIST_FAILURE = 'GET_ACTIVITY_LIST_FAILURE'

export const DETECT_ANOMALY = 'DETECT_ANOMALy'
export const DETECT_ANOMALY_REQUEST = 'DETECT_ANOMALY_REQUEST'
export const DETECT_ANOMALY_SUCCESS = 'DETECT_ANOMALY_SUCCESS'
export const DETECT_ANOMALY_FAILURE = 'DETECT_ANOMALY_FAILURE'

export const TRAIN_MODEL = 'TRAIN_MODEL'
export const TRAIN_MODEL_REQUEST = 'TRAIN_MODEL_REQUEST'
export const TRAIN_MODEL_SUCCESS = 'TRAIN_MODEL_SUCCESS'
export const TRAIN_MODEL_FAILURE = 'TRAIN_MODEL_FAILURE'