export const GET_ADMINS = 'GET_ADMINS'
export const GET_ADMINS_REQUEST = 'GET_ADMINS_REQUEST'
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS'
export const GET_ADMINS_FAILURE = 'GET_ADMINS_FAILURE'

export const DELETE_ADMINS = 'DELETE_ADMINS'
export const DELETE_ADMINS_REQUEST = 'DELETE_ADMINS_REQUEST'
export const DELETE_ADMINS_SUCCESS = 'DELETE_ADMINS_SUCCESS'
export const DELETE_ADMINS_FAILURE = 'DELETE_ADMINS_FAILURE'