export const GET_ADMINS = 'GET_ADMINS'
export const GET_ADMINS_REQUEST = 'GET_ADMINS_REQUEST'
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS'
export const GET_ADMINS_FAILURE = 'GET_ADMINS_FAILURE'