export const GET_CAREGIVERS_LIST = 'GET_CAREGIVERS_LIST'
export const GET_CAREGIVERS_LIST_REQUEST = 'GET_CAREGIVERS_LIST_REQUEST'
export const GET_CAREGIVERS_LIST_SUCCESS = 'GET_CAREGIVERS_LIST_SUCCESS'
export const GET_CAREGIVERS_LIST_FAILURE = 'GET_CAREGIVERS_LIST_FAILURE'

export const DELETE_CAREGIVERS = 'DELETE_CAREGIVERS'
export const DELETE_CAREGIVERS_REQUEST = 'DELETE_CAREGIVERS_REQUEST'
export const DELETE_CAREGIVERS_SUCCESS = 'DELETE_CAREGIVERS_SUCCESS'
export const DELETE_CAREGIVERS_FAILURE = 'DELETE_CAREGIVERS_FAILURE'

export const SAVE_CAREGIVER = 'SAVE_CAREGIVER'
export const SAVE_CAREGIVER_REQUEST = 'SAVE_CAREGIVER_REQUEST'
export const SAVE_CAREGIVER_SUCCESS = 'SAVE_CAREGIVER_SUCCESS'
export const SAVE_CAREGIVER_FAILURE = 'SAVE_CAREGIVER_FAILURE'