export const GET_DAYS_LIST = 'GET_DAYS_LIST'
export const GET_DAYS_LIST_REQUEST = 'GET_DAYS_LIST_REQUEST'
export const GET_DAYS_LIST_SUCCESS = 'GET_DAYS_LIST_SUCCESS'
export const GET_DAYS_LIST_FAILURE = 'GET_DAYS_LIST_FAILURE'

export const GET_ANOMALOUS_DAYS_LIST = 'GET_ANOMALOUS_DAYS_LIST'
export const GET_ANOMALOUS_DAYS_LIST_REQUEST = 'GET_ANOMALOUS_DAYS_LIST_REQUEST'
export const GET_ANOMALOUS_DAYS_LIST_SUCCESS = 'GET_ANOMALOUS_DAYS_LIST_SUCCESS'
export const GET_ANOMALOUS_DAYS_LIST_FAILURE = 'GET_ANOMALOUS_DAYS_LIST_FAILURE'