export const GET_LABELED_DAYS_LIST = 'GET_LABELED_DAYS_LIST'
export const GET_LABELED_DAYS_LIST_REQUEST = 'GET_LABELED_DAYS_LIST_REQUEST'
export const GET_LABELED_DAYS_LIST_SUCCESS = 'GET_LABELED_DAYS_LIST_SUCCESS'
export const GET_LABELED_DAYS_LIST_FAILURE = 'GET_LABELED_DAYS_LIST_FAILURE'