export const PREDICT_DISEASE = 'PREDICT_DISEASE'
export const PREDICT_DISEASE_REQUEST = 'PREDICT_DISEASE_REQUEST'
export const PREDICT_DISEASE_SUCCESS = 'PREDICT_DISEASE_SUCCESS'
export const PREDICT_DISEASE_FAILURE = 'PREDICT_DISEASE_FAILURE'

export const GET_PATIENTS_LIST = 'GET_PATIENTS_LIST'
export const GET_PATIENTS_LIST_REQUEST = 'GET_PATIENTS_LIST_REQUEST'
export const GET_PATIENTS_LIST_SUCCESS = 'GET_PATIENTS_LIST_SUCCESS'
export const GET_PATIENTS_LIST_FAILURE = 'GET_PATIENTS_LIST_FAILURE'

export const DELETE_PATIENTS = 'DELETE_PATIENTS'
export const DELETE_PATIENTS_REQUEST = 'DELETE_PATIENTS_REQUEST'
export const DELETE_PATIENTS_SUCCESS = 'DELETE_PATIENTS_SUCCESS'
export const DELETE_PATIENTS_FAILURE = 'DELETE_PATIENTS_FAILURE'

export const SAVE_PATIENT = 'SAVE_PATIENT'
export const SAVE_PATIENT_REQUEST = 'SAVE_PATIENT_REQUEST'
export const SAVE_PATIENT_SUCCESS = 'SAVE_PATIENT_SUCCESS'
export const SAVE_PATIENT_FAILURE = 'SAVE_PATIENT_FAILURE'