export const PREDICT_DISEASE = 'PREDICT_DISEASE'
export const PREDICT_DISEASE_REQUEST = 'PREDICT_DISEASE_REQUEST'
export const PREDICT_DISEASE_SUCCESS = 'PREDICT_DISEASE_SUCCESS'
export const PREDICT_DISEASE_FAILURE = 'PREDICT_DISEASE_FAILURE'